build:
    dependencies:
        before:
            - source .scrutinizer.setup.bash

    tests:
        override:
            -
                command: 'cd $GOPATH/src/$PROJECT && go get -t ./... && gocov test ./... -race | gocov-xml | sed "s@$GOPATH/src/$PROJECT@/home/scrutinizer/build@\" > /home/scrutinizer/build/coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
            -
                command: 'cd $GOPATH/src/$PROJECT && go-scrutinize -output_format=checkstyle-xml > checkstyle_report.xml'
                analysis:
                    file: 'checkstyle_report.xml'
                    format: 'general-checkstyle' 