build:
    dependencies:
        before:
            - source .scrutinizer.setup.bash

    tests:
        override:
            -   
                command: cd $GOPATH/src/github.com/phayes/checkstyle && go get -t ./... && gocov test ./... -race | gocov-xml > coverage.xml
                coverage:
                    file: '$GOPATH/src/github.com/phayes/checkstyle/coverage.xml'
                    format: 'clover'